from __future__ import annotations
# backend/app/routers/suburb_guides.py
#
# Read-only endpoints that serve the SEO suburb guide pages generated by
# scripts/generate_suburb_guides.py. Content is produced by a local LLM and
# lives in the suburb_guide_pages table.
import json
from fastapi import APIRouter, HTTPException, Query, Request

from ..deps import limiter
from .. import db
from ..redis import cache_get, cache_set

router = APIRouter()

CACHE_TTL = 3600  # 1h — pages change at most daily


@router.get("/suburbs/guides")
@limiter.limit("60/minute")
async def list_guides(
    request: Request,
    ta: str | None = Query(None, description="Filter by territorial authority"),
    region: str | None = Query(None, description="Filter by region"),
    limit: int = Query(5000, le=5000),
    offset: int = Query(0, ge=0),
):
    """List published guide slugs for sitemap + index pages."""
    where = ["status = 'published'"]
    params: list = []
    if ta:
        where.append("ta_name = %s")
        params.append(ta)
    if region:
        where.append("region_name = %s")
        params.append(region)
    params.extend([limit, offset])
    sql = f"""
        SELECT slug, suburb_name, ta_name, region_name,
               published_at, updated_at
        FROM suburb_guide_pages
        WHERE {' AND '.join(where)}
        ORDER BY ta_name NULLS LAST, suburb_name
        LIMIT %s OFFSET %s
    """
    async with db.pool.connection() as conn:
        cur = await conn.execute(sql, params)
        rows = cur.fetchall()
        cur = await conn.execute(
            f"SELECT COUNT(*) AS total FROM suburb_guide_pages WHERE {' AND '.join(where)}",
            params[:-2],
        )
        total = cur.fetchone()["total"]
    return {"total": total, "results": rows}


@router.get("/suburbs/guide/{slug}")
@limiter.limit("60/minute")
async def get_guide(request: Request, slug: str):
    """Return full published guide by slug (1h Redis cache)."""
    cache_key = f"suburb_guide:{slug}"
    cached = await cache_get(cache_key)
    if cached:
        return json.loads(cached)

    async with db.pool.connection() as conn:
        cur = await conn.execute(
            """
            SELECT sa2_code, slug, suburb_name, ta_name, region_name,
                   title, meta_description, h1, intro,
                   sections, faqs, key_stats, internal_links,
                   word_count, generated_at, updated_at, published_at
            FROM suburb_guide_pages
            WHERE slug = %s AND status = 'published'
            LIMIT 1
            """,
            [slug],
        )
        row = cur.fetchone()
    if not row:
        raise HTTPException(status_code=404, detail="Guide not found")

    await cache_set(cache_key, json.dumps(row, default=str), ex=CACHE_TTL)
    return row
