'use client';

import { Sparkles } from 'lucide-react';
import type { ReportSnapshot } from '@/lib/types';
import { Card, CardHead } from '@/components/new/ui/primitives';

export function HostedAISummaryNew({ snapshot }: { snapshot: ReportSnapshot }) {
  const ai = snapshot.ai_insights as unknown as Record<string, unknown> | null;
  if (!ai) return null;
  const summary = ai.executive_summary as string | undefined;
  const bottomLine = ai.bottom_line as string | undefined;
  const takeaways = (ai.key_takeaways ?? []) as string[];
  if (!summary && !bottomLine && takeaways.length === 0) return null;

  return (
    <Card>
      <CardHead title="AI analysis" meta="Generated by Claude" />
      <div className="ws-card-body" style={{ display: 'grid', gap: 14 }}>
        {summary && (
          <p style={{ margin: 0, fontSize: 14, lineHeight: 1.6, color: 'var(--ws-ink-soft)', maxWidth: '64ch' }}>
            {summary}
          </p>
        )}

        {bottomLine && (
          <div style={{
            background: 'rgba(13,115,119,.06)',
            border: '1px solid rgba(13,115,119,.20)',
            borderLeft: '3px solid var(--ws-piq)',
            borderRadius: 'var(--ws-radius-sm)',
            padding: '12px 14px',
          }}>
            <p style={{ margin: 0, fontSize: 14, fontWeight: 500, color: 'var(--ws-ink)' }}>
              {bottomLine}
            </p>
          </div>
        )}

        {takeaways.length > 0 && (
          <div>
            <h4 style={{
              margin: '0 0 8px', fontSize: 12, fontWeight: 700,
              letterSpacing: '0.08em', textTransform: 'uppercase', color: 'var(--ws-ink-mute)',
              display: 'inline-flex', alignItems: 'center', gap: 6,
            }}>
              <Sparkles size={12} style={{ color: 'var(--ws-piq)' }} />
              Key takeaways
            </h4>
            <ol style={{ listStyle: 'none', padding: 0, margin: 0, display: 'grid', gap: 8 }}>
              {takeaways.map((item, i) => (
                <li key={i} style={{ display: 'flex', alignItems: 'flex-start', gap: 10 }}>
                  <span style={{
                    flexShrink: 0,
                    width: 22, height: 22, borderRadius: 999,
                    background: 'rgba(13,115,119,.10)', color: 'var(--ws-piq)',
                    fontSize: 11, fontWeight: 700,
                    display: 'inline-grid', placeItems: 'center',
                  }}>
                    {i + 1}
                  </span>
                  <p style={{ margin: 0, fontSize: 13.5, color: 'var(--ws-ink-soft)', lineHeight: 1.55, paddingTop: 2 }}>
                    {item}
                  </p>
                </li>
              ))}
            </ol>
          </div>
        )}
      </div>
    </Card>
  );
}
