-- 0041: SEO suburb guide pages, populated by scripts/generate_suburb_guides.py
--
-- One row per SA2 suburb. Content is generated by a local LLM (Qwen via Ollama)
-- from existing suburb summary data, written once, served as SEO landing pages
-- at /suburbs/{slug}. Sections are stored as JSONB so we can add/remove sections
-- without migrations.

CREATE TABLE IF NOT EXISTS suburb_guide_pages (
    id              SERIAL PRIMARY KEY,
    sa2_code        TEXT UNIQUE NOT NULL,
    slug            TEXT UNIQUE NOT NULL,
    suburb_name     TEXT NOT NULL,
    ta_name         TEXT,
    region_name     TEXT,
    title           TEXT NOT NULL,
    meta_description TEXT NOT NULL,
    h1              TEXT NOT NULL,
    intro           TEXT NOT NULL,
    sections        JSONB NOT NULL DEFAULT '[]'::jsonb,
    faqs            JSONB NOT NULL DEFAULT '[]'::jsonb,
    key_stats       JSONB NOT NULL DEFAULT '{}'::jsonb,
    internal_links  JSONB NOT NULL DEFAULT '[]'::jsonb,
    model_used      TEXT NOT NULL,
    data_hash       TEXT NOT NULL,
    word_count      INT NOT NULL DEFAULT 0,
    status          TEXT NOT NULL DEFAULT 'draft' CHECK (status IN ('draft','published','archived')),
    generated_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    published_at    TIMESTAMPTZ
);

CREATE INDEX IF NOT EXISTS idx_suburb_guide_pages_slug ON suburb_guide_pages (slug);
CREATE INDEX IF NOT EXISTS idx_suburb_guide_pages_status ON suburb_guide_pages (status);
CREATE INDEX IF NOT EXISTS idx_suburb_guide_pages_ta_name ON suburb_guide_pages (ta_name);
CREATE INDEX IF NOT EXISTS idx_suburb_guide_pages_published_at ON suburb_guide_pages (published_at DESC)
    WHERE status = 'published';

-- updated_at trigger
CREATE OR REPLACE FUNCTION touch_suburb_guide_pages_updated_at()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = now();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_suburb_guide_pages_updated_at ON suburb_guide_pages;
CREATE TRIGGER trg_suburb_guide_pages_updated_at
    BEFORE UPDATE ON suburb_guide_pages
    FOR EACH ROW
    EXECUTE FUNCTION touch_suburb_guide_pages_updated_at();
